server:
  port: 9090

person:
  name: dsj
  age: 21
  sex: false
  tag:
    - java
    - html
    - sql


spring:
  messages:
    #相对路径 开头请勿添加斜杠
    basename: i18n/login,i18n/message

  #数据源
  # 由DataSourceAutoConfiguration DataSourceConfiguration完成装配
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stock?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    #默认数据连接池是HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5: 
    minIdl: 10: 
    maxActiv: 20:
#    配置获取连接等待超时的时间
    maxWait: 60000
#    <!-- 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 -->
    timeBetweenEvictionRunsMillis: 2000
#    <!-- 配置一个连接在池中最小生存的时间，单位是毫秒 -->
    minEvictableIdleTimeMillis: 600000
    maxEvictableIdleTimeMillis: 900000

    validationQuery: select 1
    testWhileIdl: true
    testOnBorrow: false
    testOnReturn: false

    keepAliv: true
    phyMaxUseCount: 1000

#    <!-- 配置监控统计拦截的filters -->
    filters: stat
